### ISSUE TITLE
Game Request: [Grand Cross] Yuru Plus!

### ISSUE THREAD

**Issue by Cronnicossy** [vn-tools/arc_unpacker#125]
## Game info

VNDB link: https://vndb.org/v10125
Developer: Grand Cross
Release date: 2011-11-25
Original title: ゆるプラス
English title (if available): Yuru Plus!

## Details

There is a game on the game list (list of supported games for Arc_unpacker) called Maki Fes!, also by Grand Cross. The file extension in Maki Fes! is .WARC, where as in Yuru plus!-- the game files I'm trying to extract, is .WAR. I tried anyway, of course it gave me an error-- but being its the same dev company I figured somebody else may have an easier time then me with this. Y'know, to extract the files.

I'm mostly doing this to help add content to [Visual Novel Online.](https://www.youtube.com/watch?v=KfCVuR3jFW8)

I uploaded the actual files that need extracting (not the full game), since I figured that would help speed up the process:
[Mediafire](http://www.mediafire.com/file/kystzsanz76ar8g/YuruPlusDataFilesOnly.rar)

Thanks for any assistance!

**Comment by shamashii** [comment]
From my record, crass with ZeaS war plugin done this.(-O pid=), however you should merge images after ripping.

[120317]

**Comment by Cronnicossy** [comment]
Every time I tried to use Crass (for atleast a Year now) to extract VN data for Visual Novel Online, it has never given me any successful results.

I tried -O pid= as a CUI and Parameter-- but in general Crass was doing absolutely nothing to these .WAR files. I scoured the internet for "ZeaS war plugin" and anything related to Crass, [but it didn't do anything.](https://puu.sh/vp5uW/db5d163233.png)

I have decided to upload the [VN in it's entirity](https://www.mediafire.com/?1787f08d6wf7a34), but it cannot run easily. I believe it needs a locale change-- not that running it is neccisarry to extract anyway (I'd assume). Just trying to help as much as I can. I've been pulling my hair out over trying to get these sprites extracted, for a few months now.

**Comment by shamashii** [comment]
The -O pid= should have an number like -O pid=12345 (pid = process id of the main game, running，see in the taskmon) or refer [this](https://haibara4cgrip.wordpress.com/2012/03/16/%E6%AD%BB%E7%A5%9E%E3%81%AE%E3%83%86%E3%82%B9%E3%82%BF%E3%83%A1%E3%83%B3%E3%83%88-%EF%BD%9Emenuet-of-epistula%EF%BD%9E/)

**Comment by Cronnicossy** [comment]
Thank you for all the helpful leads so far.

Through that info, I found the zeas plugin and the .Cui for RioShiina (I'm assuming that the VN Engine Grand Cross has been using, since [all the filetypes match up](https://yukict.com/bbs/thread-65028-1-1.html).)
I got somewhere new, surely. However, these files types such as .S25 and .ogv's can't be extracted further. Upon asking for help with a fellow extractor, she [showed me this.](https://cdn.discordapp.com/attachments/242084298268606465/304338452005126146/Screenshot_20170419-143208.png)

I managed to get far, even narrowing down the File I need the data from, if you see [this screenshot.](https://puu.sh/vpBla/f0327297c0.png)

The issue seems to be the .S25's. In [that same site you sent me](https://haibara4cgrip.wordpress.com/2012/03/16/%E6%AD%BB%E7%A5%9E%E3%81%AE%E3%83%86%E3%82%B9%E3%82%BF%E3%83%A1%E3%83%B3%E3%83%88-%EF%BD%9Emenuet-of-epistula%EF%BD%9E/)-- which was helpful, thank you, somebody had the same question as me. He asks the following:
Need some help
Using the latest RioShiina.cui and “crage -d -O exe=” command I was able to extract .WAR file
The problem is, what i get is file with .S25 format
What I supposed to do to convert .2S5 to png or bmp format?"

To which the response is "extract on the premise that game must be running".

The issue here, is whenever I run the .exe, it closes in a second. I cannot run it. I changed locales several times to Japenese, Chinese, Korean. However, when I Installed the Game from the SETUP.EXE as Japan locale, and went back to English (US) to run it, it gave a new error-- the one you see in that screencap I posted earlier in this text. The game still didn't start, however it didn't close-- so I extracted since the game is technically still "running".

Sadly, it's still .S25. And now I'm at a dead end wall. So close but no cigar...

**Comment by shamashii** [comment]
The [screenshot ](https://puu.sh/vpEAs/466196fe6e.png)you post seems lack an -O(Uppercase o, not zero)? it's -O pid=xxxx,not pid=xxxx ?(in window command e.g crage -d j: -O pid=xxxx)
I'm not familiar with GUI since messed java version.You should try it in cmd. If success, there should have no, or very few S25&OGV&other small junk files in output folder, just images(S25 converted to png or bmp internally).

For standard processing you probably need Jap environment first(set locale or install a true Japanese ver windows, in vmware or realmachine), then install the game(some annoying game must install to run),and then run the game, keep it running correctly and don't close(at title or some phase) and find the pid, finally use ZeaS plugin crass, cmd command: crage -d somepath -O pid=xxxx . One point, you should see some **"...Indexed file size =! actural file size...."** rolling on cmd output.

The standard steps above are stereotype and tedious, in my case(2008r2,chn), I just run exe directly from the disk(DaemonTools) and, of course it raise error and stuck(only have a window, even not arrive title page, but not exist), then get pid and cmd: crage -d somepath -O pid=xxxx , it also worked.

ps:
To see the crass plugin info, cmd : 
crage -I rioshiina
make sure output, BOLD
```
****** RioShiina ******
版权：  Y.Yamada/STUDIO よしくん
系统：  椎名里緒
封包：  .WAR .WAA .S25 .MI4 .OGV
版本：  0.4.5
作者：  痴汉公贼&**ZeaS**
时间：  Mar  2 2012 20:56:26
```

**Comment by Cronnicossy** [comment]
Yes, the error you experienced was the same one from my screenshot I assume. I couldn't run it either. As I said, on my XP Machine it runs. I used both CrageGUI and Cmd prompt as it ran, -d path -O pid=####, but it just either did nothing, say it failed to find a package, or output .S25's again.

From your last comment, I couldn't tell if you were successful, but by the 3rd "P.S" where you said to give up, I assumed it was a lost cause.

Atleast the files are uploaded. Guess we wait for assistance, but the help was appreciated greatly.

**Comment by shamashii** [comment]
> Atleast the files are uploaded.

After comparing game files you uploaded with mine, they are actually the same, so:

> I couldn't tell if you were successful



![image](https://cloud.githubusercontent.com/assets/14242157/25226628/45c704f6-25f8-11e7-9598-6d58bc5c00ab.png)


> the error you experienced was the same one from my screenshot I assume. 
It just a trick, or, a quick try if you are experienced with the tool. not 100%guaranteed.
It seem that the game engine first do some initial works, which title of gamewindow is "....2.49..." like your screenshot(I also encounter),  after that the game begin to start and the title become some other,continuously,like my screenshot, and then stuck at error. At this time I guess crass to be worked(the game finished initialization phase to which the tool need to hack, see below ). so if you just stuck on "....2.49..." I'm afraid the tool won't work for this trick.


> on my XP Machine it runs.

From zeas note, the correct way to use crass with zeas plugin with option -pid or -exe depends on the situation that you can run and play the game correctly . It is because the tool need do some hack stuff  (injection? I don't know so much on it).If you see "RioShiina: 注入失败" in cmd, it faild to inject(which not expected)and then continue out fake S25 and other files. 
So if you don't want to change your locale or install a testOS, nor failed with the trick above, your xp seem a way. Make sure the path has no unicode chars and see what cmd say.

**Comment by Cronnicossy** [comment]
After letting it run and using the proper cmd prompt input, it finally extracted. Sadly due to my crappy XP computer, my pal did it and she handed me the outcome (since it ran perfect for her).  Your screencap helped with the format of the command, since we are both new to Crass-- and there isn't a lot of info about Crass out there. I guess that is all I needed, and it doesn't need to be on Arc Unpacker.

Saves the guy some work.
Thank you so much for the help, we couldn't have done it without you.
