### ISSUE TITLE
Test-archive .g00 "It contains multiple images"

### ISSUE THREAD

**Issue by EAxp3** [vn-tools/arc_unpacker#24]
sorry for bothering again :hamster: 

real-live

![content multiple images g00](https://cloud.githubusercontent.com/assets/15073580/12186826/fcda2d02-b56b-11e5-8d84-97ad04727356.PNG)

Error-Extract 1 Image
![1 image extract](https://cloud.githubusercontent.com/assets/15073580/12186890/82893e02-b56c-11e5-87a7-55d72d62c197.PNG)

Test Archives .g00: [CG_MY29_base](https://mega.nz/#!h5ZnSZqD!lXqwoOtUPuOY5HGAECMiHy3M36ckW4ni2CyQyOVcvWU)

Source:
[append02](http://toneworks.product.co.jp/hatsukoi/kyo_append_dl.html)

thanks...I hope this problem is resolved :hammer:

**Comment by rr-** [comment]
I'm not sure what you mean, but from looking at the picture, I guess you're trying to decode only one image rather than both. If you extract both of the images separately, they'll decode just fine.

If you however want arc_unpacker to merge `base` and `face` automatically, I'm afraid it isn't possible. Unfortunately G00 images do not contain information about cross-file references so it doesn't know which image uses which. Making hardcoded guesses about file references is only going to be harmful in the future.

Because there's only a handful of such images, I believe the best course of action would be to just merge the them manually in a graphic editing program such as pinta or photoshop. You can also use bash and imagemagick like this:

    for x in *base*; do
        y=${x/base/face}
        z=${x/base/merged}
       convert -composite $x $y $z
    done
