### ISSUE TITLE
Possible problem with GXT file alpha?

### ISSUE THREAD

**Issue by DaZombieKiller** [vn-tools/arc_unpacker#25]
In Steins;Gate 0, the font files (FONT.GXT and FONT2.GXT), when converted to PNG, have completely opaque black backgrounds, which looks incorrect ingame:
![](https://images-1.discordapp.net/eyJ1cmwiOiJodHRwOi8vcHV1LnNoL21VOEM1LzdiMGZiMDIyNjkuanBnIn0.I7tFTQKPeoxoaikvvgL9bofHbV8.jpg)

The correct appearance would be the following:
![](https://images-1.discordapp.net/eyJ1cmwiOiJodHRwOi8vcHV1LnNoL21VOFJiLzkyNGMwMWE0ZTMuanBnIn0.BS5ZxoBZxJQnyBvbWhqllh0xsYQ.jpg)

**Comment by rr-** [comment]
Observations

1. There's a chance that the file is supposed to encode one color, e.g. white, and the whole rest is a giant alpha mask. But this is unlikely, because...

2. The correct text has dark border, i.e. the giant alpha mask theory doesn't seem legit. This can mean two things

   1. The image contains the border, but there is an additional alpha channel somewhere in the file which I don't read (unlikely, just checked the file)
   2. The border could have been created by the game engine itself (in which case the alpha mask theory has some justification)

3. There's also option that if the image is a GXT image then it's treated as an alpha mask, and for PNG the game expects them to have their own alpha channel.

Let's confirm some things. First, let's test if the border are applied by the game, or are read from GXT file. **Could you post a screenshot what happens if you replace `FONT` and `FONT2` with these?**

**Note: these look like nothing, but they contain white text with transparent (= white) background**.

`FONT.png`
![out](https://cloud.githubusercontent.com/assets/1045476/12791313/e08f236e-caa6-11e5-8af3-0f480585a7ac.png)
`FONT2.png`
![out2](https://cloud.githubusercontent.com/assets/1045476/12791314/e091f9cc-caa6-11e5-94ad-091ad080433e.png)

**Comment by DaZombieKiller** [comment]
![](https://images-2.discordapp.net/eyJ1cmwiOiJodHRwOi8vcHV1LnNoL21WbFRHLzY1NWQzZGFmMWQuanBnIn0.Ihap5grimqwoHbZBYNv5F1btnMQ.jpg)
it appears the outlines are generated by the engine

**Comment by rr-** [comment]
This means either

1. The whole image has a matte color, and the rest is just a giant alpha mask. This is very unlikely, as I found no evidence of this in either GXT specification or in the file itself.
2. The more probable option is that GXT are treated as masks to white color by the engine itself, and if the font is encoded as PNG, the game expects it to have alpha mask on its own.

Closing this as I suspect the option 2 is the right one, in which case you should just preprocess the PNG like above. Should you find more GXT problematic images, do not hesitate to add new issues.
