### ISSUE TITLE
Request support for .MPX files.

### ISSUE THREAD

**Issue by NhKPaNdA** [vn-tools/arc_unpacker#26]
Games that have these files are:
-Mama Shibori - https://vndb.org/v6059
-Mama Shibori 2 - https://vndb.org/v6058
-Mama Mahjong - https://vndb.org/v3016

Developer's website: http://www.complets.co.jp

**Comment by rr-** [comment]
The graphics and audio are well supported - MPX files are just scripts. I've checked the game's code and they don't seem to contain anything interesting - the script contents are all binary, so you'd need a proper script (de)compiler in order to extract the game text. This is a subject for a separate project and useful mainly for translation projects, so I'm closing the issue.
