### ISSUE TITLE
Error decoding (Premature end of file)

### ISSUE THREAD

**Issue by NhKPaNdA** [vn-tools/arc_unpacker#28]
Fails to convert the .tlg to a .png when extracting from the fgimage.xp3.

Heres the file: 
[maf_1_2_c.zip](https://github.com/vn-tools/arc_unpacker/files/116289/maf_1_2_c.zip)

**Comment by rr-** [comment]
The file is definitely truncated (it has 65536 bytes while it should have at least 416350 bytes), so @arc_unpacker@'s TLG decoder is right about this one. Can I see @.xp3@ or the title of the problematic game?

**Comment by NhKPaNdA** [comment]
.xp3 is 318mb, too big for me to upload.
The game's title is: Mama Mama Mama
Vndb link: https://vndb.org/v1621

**Comment by rr-** [comment]
I've just checked the game myself. The archive they ship is corrupt - the file is definitely truncated: XP3 reports the size as 65536 rather than ~416350 (this number is taken from the file header that decodes correctly), and when I checked the archive with a hex editor, there's no hidden extra data inside - right those 65536 are immediately followed by another file.
