### ISSUE TITLE
Dies Irae std::bad_alloc error

### ISSUE THREAD

**Issue by NhKPaNdA** [vn-tools/arc_unpacker#34]
There is an error when decoding the picture.lib file.
For Dies Irae ~Amantes amentes~:
error decoding "bg" std::bad_alloc
error decoding "chara" std::bad_alloc
error decoding "event" std::bad_alloc
"mask" decodes correctly

For Dies irae ~Acta est Fabula~
error decoding "bg" std::bad_alloc
"chara" decodes correctly
error decoding "bg" std::bad_alloc
"mask" decodes correctly

Vndb: https://vndb.org/v548
Both are Regular Editions with Install versions. (No patches applied)
Both were tested on Windows 8.1 Pro 64bit

**Comment by rr-** [comment]
Ok... generally these archives contain nested archives that are *very* big (some have 1.5GB). I have 8GB RAM, so this is not an issue for me.

To work around this issue, please:

* try running `arc_unpacker` with `-t=1` so that it tries to decode only one thing at once, which should theoretically reduce memory consumption.
* if this still does not work, try running it with `-t=1 --no-recurse` so that it doesn't keep the file in the memory, but instead saves it to disk. Then try to unpack the extracted files normally.

Please let me know if it works.

**Comment by NhKPaNdA** [comment]
Using -t=1 and -t=1 --no-recurse is able to decode
"mask"
"chara"
"bg"
But still gives the same error for "event" for both Amantes amentes and Acta est Fabula.

I have 4gbs of ram, is that really not enough to decode the event cg ?

**Comment by rr-** [comment]
I tried to change the algorithm to reduce memory footprint. Please let me know if it helps you (nightly build should run in about 4 hours).

**Comment by NhKPaNdA** [comment]
Tried it out with the new build.
Decoding normally, with -t=1 or with -t=1 --no-recurse still gives that error for "event"

**Comment by rr-** [comment]
I've further reduced the number of copies being made.

**Comment by rr-** [comment]
Things should improve with recent update.

**Comment by NhKPaNdA** [comment]
Tested it with last nights build. Works perfectly without -t=1 or -t=1 --no-recurse. Great job.

Just wish they didn't make some of the cgs like a piece the puzzle game

**Comment by rr-** [comment]
:tada:

Unfortunately the gfx files do not contain info about cross references so it's not quite possible to merge the graphics (short of making some fragile guesswork based on file names, or parsing the scripts).
