### ISSUE TITLE
Game request: [Abogado Powers][020830]Pigeon Blood

### ISSUE THREAD

**Issue by marconii2002** [vn-tools/arc_unpacker#86]
## Game info

VNDB link: https://vndb.org/v752
Developer: Abogado Powers
Release date: 30-08-2002
Original title: PIGEON BLOOD
English title (if available): 

## Details

This time old game, on mail I will send you this game. Can you add support for this game

**Comment by rr-** [comment]
Teaser:

![backyard](https://cloud.githubusercontent.com/assets/1045476/19491392/0dd58880-9573-11e6-985a-7e021f2eb80d.png)

**Comment by rr-** [comment]
I've pushed image and archive decoding:

- 3d48d934179ee946f0137cd00bfffab66247916d: dec/abogado/dsk: initial support
- 821240e455d4d63fce0000d4d67989ac884ef193: dec/abogado/kg: initial support

Audio will take some more time, but hopefully I should finish it by the end of this week (no promises though cause I'm on tight schedule).

**Comment by marconii2002** [comment]
I'm ripping CGs from various games, to me images are more important. Audio can wait.

**Comment by rr-** [comment]
In that case, the image support is available in the latest nightly :)

**Comment by rr-** [comment]
Done:

- 3d48d934179ee946f0137cd00bfffab66247916d: dec/abogado/dsk: initial support
- 821240e455d4d63fce0000d4d67989ac884ef193: dec/abogado/kg: initial support
- 1f9110f841426c6143581a90a836bdcf9e23e9f5: dec/abogado/v: initial support
- e950392b2c0e7936df44995ce1a9cd3e41bfddee: docs: add [Abogado Powers][020830]Pigeon Blood

Example image:

![sp78](https://cloud.githubusercontent.com/assets/1045476/19622993/f60059e4-98b8-11e6-9859-39dd02ac80b1.png)

Changes should appear in tonight's build around 1 AM UTC: https://tmp.sakuya.pl/au/

**Known problem**: for certain event images, the game adds corrupt alpha channel which it internally ignores, but `au` has no way to distinguish it from other images and thus renders what it sees. This can sometimes lead to visual glitches like in the example above. I spent around 1.5 h to make 100% sure the game decodes alpha channel exactly like this and it does - it's just that when it draws on the screen the bottommost image in the renderer stack, the alpha is simply discarded. So in order to obtain correct image, you need to discard the mask manually in any graphic program.

(The only choice I had was to hardcode file names that shouldn't use image masks, and I'd obviously rather avoid depending on the file names to work around game's internal bugs.)

If you experience any other problems, feel free to reopen the issue.
